//-----------------------------------------------------------------------
// <copyright file="DailyUserActivity.cs" company="Microsoft">
//     Copyright (c) Microsoft. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Microsoft.RewardsIntl.Platform.DataAccess.SharedDAObjects
{
    using System.Runtime.Serialization;
    using Microsoft.RewardsIntl.Platform.DataAccess.Common;
    using Microsoft.RewardsIntl.Platform.DataAccess.Common.MessageQueues;

    [DAClass(QueueName = MessageQueueName.DailyUserActivity)]
    [DataContract(Name = "DUA", Namespace = "")]
    public class DailyUserActivity : IQueueData
    {
        /// <summary>
        /// Id of the message
        /// </summary>
        public string MessageId { get; set; }

        /// <summary>
        /// Unique ID generated by the Queue everytime a message is popped from the queue
        /// </summary>
        public string PopReceipt { get; set; }

        /// <summary>
        /// UserBruid, primary key for a record in DailyActivitySearch table
        /// </summary>
        [DataMember(Order = 0, Name = "B")]
        public string Bruid { get; set; }

        /// <summary>
        /// Date hour bucket, row key for a record in DailyActivitySearch table
        /// </summary>
        [DataMember(Order = 1, Name = "D")]
        public string Date { get; set; }
    }
}