// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IQueueCommonData.cs" company="Microsoft">
//     Copyright (c) Microsoft. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Microsoft.RewardsIntl.Platform.DataAccess.Common.MessageQueues
{
    public interface IQueueData
    {
        /// <summary>
        /// Id of the message
        /// </summary>
        string MessageId { get; set; }

        /// <summary>
        /// Unique ID generated by the Queue everytime a message is popped from the queue
        /// </summary>
        string PopReceipt { get; set; }
    }
}
