//-----------------------------------------------------------------------
// <copyright file="UserSearchRecord.cs" company="Microsoft">
//     Copyright (c) Microsoft. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Microsoft.RewardsIntl.Platform.DataAccess.SharedDAObjects.LogDataDefinitions
{
    using System;
    using System.Runtime.Serialization;
    using Microsoft.RewardsIntl.Platform.DataAccess.Common;
    using Microsoft.RewardsIntl.Platform.DataAccess.Common.MessageQueues;

    [DAClass(QueueName = MessageQueueName.ProcessedSearchData)]
    [DataContract(Name = "USR", Namespace = "")]
    public class UserSearchRecord : IQueueData
    {
        /// <summary>
        /// Id of the message
        /// </summary>
        public string MessageId { get; set; }

        /// <summary>
        /// Unique ID generated by the Queue everytime a message is popped from the queue
        /// </summary>
        public string PopReceipt { get; set; }
        
        /// <summary>
        /// UTC date time to denote when the search is made
        /// </summary>
        [DataMember(Order = 0, Name = "D")]
        public string Date { get; set; }

        /// <summary>
        /// UserBruid to identify user
        /// </summary>
        [DataMember(Order = 1, Name = "B")]
        public string UserBruid { get; set; }

        /// <summary>
        /// Queries done by the user for the day
        /// </summary>
        [DataMember(Order = 2, Name = "QC")]
        public int QueryCount { get; set; }

        /// <summary>
        /// Credits earned by the user for the day
        /// </summary>
        [DataMember(Order = 3, Name = "C")]
        public int CreditsEarned { get; set; }

        /// <summary>
        /// Spam count detected by the spam filter
        /// </summary>
        [DataMember(Order = 4, Name = "SC")]
        public int SpamCount { get; set; }
    }
}
